server:
  port: 8443
  http:
    port: 80
  ssl:
    enabled: false

spring:
  datasource:
    url: jdbc:h2:file:./data/certdb
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

acme:
  server:
    url: https://acme-v02.api.letsencrypt.org/directory
  account:
    email: admin@example.com
  security:
    key-store-type: PKCS12
    key-store-password: changeit
    allow-http: true

logging:
  level:
    com.ssltest: DEBUG 